#!/bin/sh
CURRENT_DIR=$(cd ${0%/*} && pwd -P)
SOURCE_DIR=/source

get_info() {
  cd $SOURCE_DIR && \
    mix run \
      --no-compile \
      --no-deps-check \
      --no-start \
      -r $CURRENT_DIR/app_info.exs \
      -e "IO.puts AppInfo.${1}"
}

case $1 in
  name|version|distillery|phoenix)
    get_info $1
    ;;
  debug)
    echo "CURRENT_DIR: ${CURRENT_DIR}"
    echo "SOURCE_DIR:  ${SOURCE_DIR}"
esac
# ret=$?
