#!/bin/sh
CURRENT_DIR=$(cd ${0%/*} && pwd -P)
APP_DIR=$(cd ${CURRENT_DIR}/../app && pwd -P)

get_info() {
  cd $APP_DIR && \
    mix run \
      --no-compile \
      --no-deps-check \
      --no-start \
      -r $CURRENT_DIR/app_info.exs \
      -e "IO.puts AppInfo.${1}"
}

case $1 in
  name|version|exrm|phoenix)
    get_info $1
    ;;
  debug)
    echo "CURRENT_DIR: ${CURRENT_DIR}"
    echo "APP_DIR:     ${APP_DIR}"
esac
# ret=$?
